package com.example.advstatus;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Campaign implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean isCritcallyOutOfStock;
	private double starLevel;
	private double budget;

	private java.lang.String result;

	public Campaign() {
	}

	@Override
	public String toString() {
		return "Campaign [budget=" + budget + ", isCritcallyOutOfStock=" + isCritcallyOutOfStock + ", result=" + result
				+ ", starLevel=" + starLevel + "]";
	}

	public boolean isIsCritcallyOutOfStock() {
		return this.isCritcallyOutOfStock;
	}

	public void setIsCritcallyOutOfStock(boolean isCritcallyOutOfStock) {
		this.isCritcallyOutOfStock = isCritcallyOutOfStock;
	}

	public double getStarLevel() {
		return this.starLevel;
	}

	public void setStarLevel(double starLevel) {
		this.starLevel = starLevel;
	}

	public double getBudget() {
		return this.budget;
	}

	public void setBudget(double budget) {
		this.budget = budget;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public Campaign(boolean isCritcallyOutOfStock, double starLevel,
			double budget, java.lang.String result) {
		this.isCritcallyOutOfStock = isCritcallyOutOfStock;
		this.starLevel = starLevel;
		this.budget = budget;
		this.result = result;
	}

}